<a href="https://colab.research.google.com/github/saimeonver/PythonExercise/blob/main/PandasExercises1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Görev1: List Comph yapısı kullanrak car_cashes verisindeki numeric
#değişkenlerin isimlerini büyük harfe çevirinix ve başına NUM ekleyin

import seaborn as sns
df = sns.load_dataset("car_crashes")
df.columns

Index(['total', 'speeding', 'alcohol', 'not_distracted', 'no_previous',
       'ins_premium', 'ins_losses', 'abbrev'],
      dtype='object')

In [ ]:
['NUM' + col.upper() for col in df.columns  if df[col].dtype!='object']

['NUMTOTAL',
 'NUMSPEEDING',
 'NUMALCOHOL',
 'NUMNOT_DISTRACTED',
 'NUMNO_PREVIOUS',
 'NUMINS_PREMIUM',
 'NUMINS_LOSSES']

In [3]:
['NUM' + col.upper() if df[col].dtype!='object'else col.upper() for col in df.columns]

['NUMTOTAL',
 'NUMSPEEDING',
 'NUMALCOHOL',
 'NUMNOT_DISTRACTED',
 'NUMNO_PREVIOUS',
 'NUMINS_PREMIUM',
 'NUMINS_LOSSES',
 'ABBREV']

In [ ]:
df.head()

,total,speeding,alcohol,not_distracted,no_previous,ins_premium,ins_losses,abbrev
0,18.8,7.332,5.640,18.048,15.040,784.55,145.08,AL
1,18.1,7.421,4.525,16.290,17.014,1053.48,133.93,AK
2,18.6,6.510,5.208,15.624,17.856,899.47,110.35,AZ
3,22.4,4.032,5.824,21.056,21.280,827.34,142.39,AR
4,12.0,4.200,3.360,10.920,10.680,878.41,165.63,CA

In [ ]:
#Görev2: List Comph yapısı kullanarak car_crashes versindeki isminde
#'no' barındaırmayan değişkenlerin sonuna "FLAG" yazalım

[col.upper() + "_FLAG"
 if "no" not in col.lower()
 else col.upper()
 for col in df.columns
 ]

['TOTAL_FLAG',
 'SPEEDING_FLAG',
 'ALCOHOL_FLAG',
 'NOT_DISTRACTED',
 'NO_PREVIOUS',
 'INS_PREMIUM_FLAG',
 'INS_LOSSES_FLAG',
 'ABBREV_FLAG']

In [ ]:
#görev3 : Lis Comph ypaısı kullanrak aşağıda verilenn değişken isimlerinin
#farklı olan değişkenlerin isimlerini seçin ve yeni bir df oluştur

og_list = ["abbrev", "no_previous"]

In [ ]:
new_cols=[col for col in df.columns if col.lower() not in og_list]

In [ ]:
new_cols

['total', 'speeding', 'alcohol', 'not_distracted', 'ins_premium', 'ins_losses']

In [ ]:
#yeni kolonlardan yeni bir df oluşturma
new_df=df[new_cols]
#yada new_df = pd.DataFrame(df[new_cols])

In [6]:
#Pandas Alıştırmalar
#1 seaborn kütüphanesinden titanic veri setini tanımla
import pandas as pd
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
#herbir sütuna ait unique değerleri bulun
df.nunique()

survived         2
pclass           3
sex              2
age             88
sibsp            7
parch            7
fare           248
embarked         3
class            3
who              3
adult_male       2
deck             7
embark_town      3
alive            2
alone            2
dtype: int64

In [ ]:
from numpy import unique_values
#görev 4: pclass değişkeninin unique değerlerinin sayısını bul
df['pclass'].nunique()

3

In [ ]:
#görev 5: pclass ve parch değişkenlerinin unique değerlerinin
#sayısını bul
df[['pclass','parch']].nunique()

pclass    3
parch     7
dtype: int64

In [ ]:
#görev6 : embarked değişkenin tipini bulun. tipini category olarak değiştir
#ve tekrar kontrol et
df["embarked"].dtype

dtype('O')

In [ ]:
df["embarked"] = df["embarked"].astype("category")

In [ ]:
df["embarked"].dtype

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False, categories_dtype=object)

In [ ]:
#grev 7 : embarked değeri C olanların tüm bilgilerini gösterin

df.loc[df["embarked"] == "C"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
866,1,2,female,27.0,1,0,13.8583,C,Second,woman,False,NaN,Cherbourg,yes,False
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True

In [7]:
#görev 8: embarked değeri S olmaynaları göster

df.loc[df["embarked"] != 'S']

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
16,0,3,male,2.0,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
879,1,1,female,56.0,0,1,83.1583,C,First,woman,False,C,Cherbourg,yes,False
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
df[df["embarked"] != "S"]["embarked"].unique()

array(['C', 'Q', nan], dtype=object)

In [ ]:
#görev 9 : Yaşı 30 dan küçük ve kadın olan yolcuların tüm bilgilerini göster
df.loc[(df["sex"] == "female") & (df["age"] < 30)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
14,0,3,female,14.0,0,0,7.8542,S,Third,child,False,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
874,1,2,female,28.0,1,0,24.0000,C,Second,woman,False,NaN,Cherbourg,yes,False
875,1,3,female,15.0,0,0,7.2250,C,Third,child,False,NaN,Cherbourg,yes,True
880,1,2,female,25.0,0,1,26.0000,S,Second,woman,False,NaN,Southampton,yes,False
882,0,3,female,22.0,0,0,10.5167,S,Third,woman,False,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True

In [ ]:
#fare'i 500 den büyük veya yaşı 70 den büyük yolcularaın bilgilerini göster

df.loc[(df["fare"] > 500) | (df["age"] > 70)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
#görev 11 : her bir değişkende boş değerlerin toplamını bul

df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
#görev 12 : who değişenini dataframeden çıkar

df.drop("who",axis = 1, inplace= True)

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,True,NaN,Southampton,no,True

In [ ]:
#görev 13: deck değişkenindeki boş değerleri deck değişkeninin en çok tekrar
#eden (mod) ile doldur

In [9]:
mode_value = df["deck"].mode()[0]
df["deck"] = df["deck"].fillna(mode_value)
df["deck"].isnull().sum()

np.int64(0)