<a href="https://colab.research.google.com/github/saimeonver/PythonExercise/blob/main/Pandas4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Apply ve Lambda
#apply : satır ve sütunlarda fonksiyon çalışmaya yarar
#lambda :bir fonksiyon tanımlama şeklidir. Kullan at fonksiyondur

In [2]:
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 500)
df = sns.load_dataset("titanic")
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True

In [3]:
df["age2"] = df["age"] * 2

In [4]:
df["age3"] = df["age"] * 3

In [5]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone  age2   age3
0         0       3    male  22.0      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False  44.0   66.0
1         1       1  female  38.0      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False  76.0  114.0
2         1       3  female  26.0      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True  52.0   78.0
3         1       1  female  35.0      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False  70.0  105.0
4         0       3    male  35.0      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True  70.0  105.0

In [7]:
(df["age"]/10).head()

0    2.2
1    3.8
2    2.6
3    3.5
4    3.5
Name: age, dtype: float64

In [8]:
(df["age2"]/10).head()

0    4.4
1    7.6
2    5.2
3    7.0
4    7.0
Name: age2, dtype: float64

In [9]:
(df["age3"]).head()

0     66.0
1    114.0
2     78.0
3    105.0
4    105.0
Name: age3, dtype: float64

In [10]:
#her biri için tek tek işlem yapacağıma döngü yazarım
for col in df.columns:
  if "age" in col:
    print(col)

age
age2
age3

In [12]:
for col in df.columns:
  if "age" in col:
    print((df[col]/10).head())

0    2.2
1    3.8
2    2.6
3    3.5
4    3.5
Name: age, dtype: float64
0    4.4
1    7.6
2    5.2
3    7.0
4    7.0
Name: age2, dtype: float64
0     6.6
1    11.4
2     7.8
3    10.5
4    10.5
Name: age3, dtype: float64

In [13]:
for col in df.columns:
  if "age" in col:
    df[col]=df[col]/10

In [14]:
df.head()

   survived  pclass     sex  age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone  age2  age3
0         0       3    male  2.2      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False   4.4   6.6
1         1       1  female  3.8      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False   7.6  11.4
2         1       3  female  2.6      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True   5.2   7.8
3         1       1  female  3.5      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False   7.0  10.5
4         0       3    male  3.5      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True   7.0  10.5

In [15]:
#apply ile nasıl yaparım
df[["age", "age2" , "age3"]].apply(lambda x : x/10).head()

    age  age2  age3
0  0.22  0.44  0.66
1  0.38  0.76  1.14
2  0.26  0.52  0.78
3  0.35  0.70  1.05
4  0.35  0.70  1.05

In [16]:
df.loc[:, df.columns.str.contains("age")].apply(lambda x : x/10).head()

    age  age2  age3
0  0.22  0.44  0.66
1  0.38  0.76  1.14
2  0.26  0.52  0.78
3  0.35  0.70  1.05
4  0.35  0.70  1.05

In [ ]:
#değerleri standartlaştırdık
df.loc[:, df.columns.str.contains("age")].apply(lambda x: (x - x.mean()) / x.std())

In [17]:
#değerleri standartlaştırmanın diğer yolu

def standart_scale(col_name):
  return (col_name - col_name.mean()) / col_name.std()

df.loc[: , df.columns.str.contains("age")].apply(standart_scale).head()

        age      age2      age3
0 -0.530005 -0.530005 -0.530005
1  0.571430  0.571430  0.571430
2 -0.254646 -0.254646 -0.254646
3  0.364911  0.364911  0.364911
4  0.364911  0.364911  0.364911

In [ ]:
#kalıcı şekilde değişikliği gerçekleştirdim
df.loc[:, ["age", "age2", "age3"]]= df.loc[:, df.columns.str.contains("age")].apply(standart_scale)

In [18]:
#yukarıdaki işlemin diğer yolu
df.loc[:, df.columns.str.contains("age")]= df.loc[:, df.columns.str.contains("age")].apply(standart_scale)
df.head()

   survived  pclass     sex       age  sibsp  parch     fare embarked  class    who  adult_male deck  embark_town alive  alone      age2      age3
0         0       3    male -0.530005      1      0   7.2500        S  Third    man        True  NaN  Southampton    no  False -0.530005 -0.530005
1         1       1  female  0.571430      1      0  71.2833        C  First  woman       False    C    Cherbourg   yes  False  0.571430  0.571430
2         1       3  female -0.254646      0      0   7.9250        S  Third  woman       False  NaN  Southampton   yes   True -0.254646 -0.254646
3         1       1  female  0.364911      1      0  53.1000        S  First  woman       False    C  Southampton   yes  False  0.364911  0.364911
4         0       3    male  0.364911      0      0   8.0500        S  Third    man        True  NaN  Southampton    no   True  0.364911  0.364911

In [19]:
#birleştirme (Join) işlemleri

import numpy as np
import pandas as pd
m = np.random.randint(1, 30, size = (5,3))
df1 = pd.DataFrame(m, columns = ["var1", "var2", "var3"])
df2 = df1 + 99

In [20]:
pd.concat([df1,df2]) # iki dataframi birleştirdim

   var1  var2  var3
0    27    22    18
1    26    11    22
2     2    27    28
3    28     7    19
4    12     2    19
0   126   121   117
1   125   110   121
2   101   126   127
3   127   106   118
4   111   101   118

In [21]:
pd.concat([df1,df2], ignore_index = True)

   var1  var2  var3
0    27    22    18
1    26    11    22
2     2    27    28
3    28     7    19
4    12     2    19
5   126   121   117
6   125   110   121
7   101   126   127
8   127   106   118
9   111   101   118

In [22]:
#Merge ile birleştirme işlemleri

df1 = pd.DataFrame({'employees': ['john', 'dennis','mark','maria'],
                    'group': ['accounting','engineering','enginnering','hr']})
df2 = pd.DataFrame({'employees': ['mark','john','dennis','maria'],'start_date':[2010,2009,2014,2019]})

In [23]:
df1

  employees        group
0      john   accounting
1    dennis  engineering
2      mark  enginnering
3     maria           hr

In [24]:
df2

  employees  start_date
0      mark        2010
1      john        2009
2    dennis        2014
3     maria        2019

In [25]:
pd.merge(df1,df2)
pd.merge(df1, df2, on='employees')

  employees        group  start_date
0      john   accounting        2009
1    dennis  engineering        2014
2      mark  enginnering        2010
3     maria           hr        2019

In [26]:
#amaç : her çalışanın müdürünün bilgisine erişmek istiyoruz
df3 = pd.merge(df1,df2)

In [27]:
df4 = pd.DataFrame({'group': ['accounting','engineering','hr'],'manager': ['Caner','Mustafa','Berkcan']})
#

In [29]:
pd.merge(df3,df4)

  employees        group  start_date  manager
0      john   accounting        2009    Caner
1    dennis  engineering        2014  Mustafa
2     maria           hr        2019  Berkcan