<a href="https://colab.research.google.com/github/saimeonver/PythonExercise/blob/main/Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#PANDAS

In [2]:
#Veri okuma(Reading Data)
#Veriye Hızlı Bakış(Quick Look at Data)
#Pandasta Seçim İşlemleri(Selection in Pandas)
#Toplulaştırma ve Gruplama (Aggregation and Grouping)
#Apply ve Lambda
#Birleştirme (Join) İşlemleri

In [6]:
import pandas as pd
s = pd.Series([10, 77, 12, 4, 5])
s

0    10
1    77
2    12
3     4
4     5
dtype: int64

In [ ]:
#Bu şekilde index bilgilerine göre veriyi tutar pandas

In [5]:
type(s)

pandas.core.series.Series

In [7]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [8]:
s.dtype#tip bilgisi

dtype('int64')

In [9]:
s.size#eleman sayısı

5

In [10]:
s.ndim#boyut

1

In [12]:
s.values#değerler

array([10, 77, 12,  4,  5])

In [13]:
type(s.values)

numpy.ndarray

In [15]:
s.head(3)#ilk üç satır

0    10
1    77
2    12
dtype: int64

In [16]:
s.tail(3)#son 3 satır

2    12
3     4
4     5
dtype: int64

In [26]:
#Veri Okuma

import pandas as pd

df = pd.read_csv("sample_data/advertising.csv")

In [28]:
df.head()

      TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [29]:
#Veriye Hızlı bakış

import pandas as pd
import seaborn as sns

In [30]:
df = sns.load_dataset("titanic")

In [31]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [32]:
#survived değişkeni ana odaktır bağımlı değişken hedef değişkendir
# 0 ve 1 e göre hayatta kalıp kalmama durumuna bakar

In [33]:
df.tail()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
886,0,2,male,27.0,0,0,13.00,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.00,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.45,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.00,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.75,Q,Third,man,True,NaN,Queenstown,no,True

In [34]:
df.shape

(891, 15)

In [35]:
df.ndim

2

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
#object ve category ikiside katogorik değişkendir
#genel hatlarıyla aynıdır
#burada tiplerden kaç adet oldupunu gösterir
 #bool(2), category(2), float64(2), int64(4), object(5)

In [38]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [39]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [41]:
#verinin özeti
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [42]:
df.isnull().values.any()#eksik veri var mı

np.True_

In [43]:
df.isnull().values

array([[False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       ...,
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False],
       [False, False, False, ..., False, False, False]])

In [44]:
#her bir değişkende kaç adet eksik değer var
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [45]:
#cinsiyete göre count alalım
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [46]:
#Pandas'ta Seçim işlemleri (selection in pandas)
import pandas as pd
import seaborn as sns
df = sns.load_dataset("titanic")

In [47]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [48]:
df.index

RangeIndex(start=0, stop=891, step=1)

In [49]:
df[0:13]#13 hariçtir

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [50]:
df.drop(0, axis=0).head()
#0 ıncı indexi sildik. kalıcı silme değil

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True

In [51]:
#bazı indexleri silmek istersem
delete_indexes = [1,3, 5, 7]
df.drop(delete_indexes,axis=0).head(10)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
8,1,3,female,27.0,0,2,11.1333,S,Third,woman,False,NaN,Southampton,yes,False
9,1,2,female,14.0,1,0,30.0708,C,Second,child,False,NaN,Cherbourg,yes,False
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
12,0,3,male,20.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False

In [ ]:
#kalıcı silmek için
#df = df.drop(delete_indexes,axis=0).head(10)

In [ ]:
#2. kalıcı silmek için yol
#df.drop(delete_indexes,axis=0, inplace=True)

In [52]:
#Değişkeni Indexe çevirmek

df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [53]:
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [55]:
df.index = df["age"]#index için ekledik

In [56]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,,
22.0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27.0,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
19.0,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
NaN,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
26.0,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
32.0,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [57]:
df.drop("age",axis=1).head()#geçici sildik

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [58]:
df.drop("age", axis=1, inplace= True)#kalıcı sildik

In [60]:
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
#Indexi değikene çevirelim

In [61]:
df.index

Index([22.0, 38.0, 26.0, 35.0, 35.0,  nan, 54.0,  2.0, 27.0, 14.0,
       ...
       33.0, 22.0, 28.0, 25.0, 39.0, 27.0, 19.0,  nan, 26.0, 32.0],
      dtype='float64', name='age', length=891)

In [62]:
df["age"]= df.index#değişen alarak ekledik

In [63]:
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age
age,,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,22.0
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,38.0
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,26.0
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,35.0
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,35.0

In [65]:
#2. yol
df.drop("age",axis=1,inplace=True)#age i sildik. axis =1 sütun demek
df.reset_index().head()#indexi kendi otomatik oluşturdu
#age i de farklı bir kolona yeni bir kolon olarak tanımladı

,age,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True