<a href="https://colab.research.google.com/github/saimeonver/PythonExercise/blob/main/Pandas3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Değişkenler üzerinde işlemler

In [ ]:
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns', None)#tüm sütunları getirir
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
"age" in df

True

In [ ]:
df["age"].head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [ ]:
df.age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [ ]:
type(df["age"].head())#Önemli tek parantezli oldupunda pandas serisi

pandas.core.series.Series

In [ ]:
df[["age"]].head()

    age
0  22.0
1  38.0
2  26.0
3  35.0
4  35.0

In [ ]:
type(df[["age"]].head())# Önemli çift parantezli olduğunda data frame oluor

pandas.core.frame.DataFrame

In [ ]:
df[["age","alive"]]

      age alive
0    22.0    no
1    38.0   yes
2    26.0   yes
3    35.0   yes
4    35.0    no
..    ...   ...
886  27.0    no
887  19.0   yes
888   NaN    no
889  26.0   yes
890  32.0    no

[891 rows x 2 columns]

In [ ]:
col_names = ["age","adult_male","alive"]

In [ ]:
df[col_names]

      age  adult_male alive
0    22.0        True    no
1    38.0       False   yes
2    26.0       False   yes
3    35.0       False   yes
4    35.0        True    no
..    ...         ...   ...
886  27.0        True    no
887  19.0       False   yes
888   NaN       False    no
889  26.0        True   yes
890  32.0        True    no

[891 rows x 3 columns]

In [ ]:
df["age2"]= df["age"]**2
#olmayan bir kolon adı girildiğinde onu ekler

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age2
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0

In [ ]:
df["age3"]= df["age"] / df["age2"]

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age2,age3
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0,0.045455
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0,0.026316
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0,0.038462
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0,0.028571
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0,0.028571

In [ ]:
df.drop("age3", axis=1).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,age2
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,484.0
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,1444.0
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,676.0
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,1225.0
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,1225.0

In [ ]:
df.drop(col_names , axis=1).head()#silme işlemi yaptım

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,deck,embark_town,alone,age2,age3
0,0,3,male,1,0,7.2500,S,Third,man,NaN,Southampton,False,484.0,0.045455
1,1,1,female,1,0,71.2833,C,First,woman,C,Cherbourg,False,1444.0,0.026316
2,1,3,female,0,0,7.9250,S,Third,woman,NaN,Southampton,True,676.0,0.038462
3,1,1,female,1,0,53.1000,S,First,woman,C,Southampton,False,1225.0,0.028571
4,0,3,male,0,0,8.0500,S,Third,man,NaN,Southampton,True,1225.0,0.028571

In [ ]:
#kolonlarda age geçenleri getirir
df.loc[:, df.columns.str.contains("age")].head()

    age    age2      age3
0  22.0   484.0  0.045455
1  38.0  1444.0  0.026316
2  26.0   676.0  0.038462
3  35.0  1225.0  0.028571
4  35.0  1225.0  0.028571

In [ ]:
#bunun değilini yapalım
#kolonlarda age geçmeyenler
df.loc[:, ~df.columns.str.contains("age")].head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.loc[:,df.columns.str.contains("embark")].head()

  embarked  embark_town
0        S  Southampton
1        C    Cherbourg
2        S  Southampton
3        S  Southampton
4        S  Southampton

In [ ]:
#iloc & loc
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns',None)
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
# iloc : integer based selection (indexe bakarak seçer)
df.iloc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True

In [ ]:
df.iloc[0,0]

np.int64(0)

In [ ]:
#loc :label based selection(içeridği metne göe ya da kolon adona göre seçim yapar)
#0 ve 3 aralığını alındığında 3 ü yüde dahil  eder
df.loc[0:3]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False

In [ ]:
df.iloc[0:3, 0:3]
#bunun yerine df.iloc[0:3, "age"] kullanamam hata alırım benden index bekliyor

In [ ]:
df.loc[0:3,"age"]

0    22.0
1    38.0
2    26.0
3    35.0
Name: age, dtype: float64

In [ ]:
col_names = ["age", "embarked","alive"]

df.loc[0:3, col_names]

    age embarked alive
0  22.0        S    no
1  38.0        C   yes
2  26.0        S   yes
3  35.0        S   yes

In [ ]:
#Koşullu Seçim (Conditional Selection)

import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns',None)
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df[df["age"] > 50].head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
33,0,2,male,66.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
54,0,1,male,65.0,0,1,61.9792,C,First,man,True,B,Cherbourg,no,False

In [ ]:
df[df["age"] >50].count()

survived       64
pclass         64
sex            64
age            64
sibsp          64
parch          64
fare           64
embarked       63
class          64
who            64
adult_male     64
deck           33
embark_town    63
alive          64
alone          64
dtype: int64

In [ ]:
df[df["age"] > 50]["age"].count()

np.int64(64)

In [ ]:
df.loc[df["age"] > 50, "class"].head()

6      First
11     First
15    Second
33    Second
54     First
Name: class, dtype: category
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
df.loc[df["age"] >50,"class"].head() # bir koşul bir sütun seçtim

6      First
11     First
15    Second
33    Second
54     First
Name: class, dtype: category
Categories (3, object): ['First', 'Second', 'Third']

In [ ]:
df.loc[df["age"] >50, ["age","class"]].head() #bir koşul iki sütun

     age   class
6   54.0   First
11  58.0   First
15  55.0  Second
33  66.0  Second
54  65.0   First

In [ ]:
#ikinci  koşulu eklerken araya & konur iki koşulun dışına da ayrı ayrı parantez konur
df.loc[(df["age"]>50) & (df["sex"] == "male"), ["age","class"]].head()

     age   class
6   54.0   First
33  66.0  Second
54  65.0   First
94  59.0   Third
96  71.0   First

In [ ]:
df.loc[(df["age"]>50 )
& (df["sex"]== "male")
& (df["embark_town"] == "Cherbourg"),
  ["age","class","embark_town"]].head()

      age  class embark_town
54   65.0  First   Cherbourg
96   71.0  First   Cherbourg
155  51.0  First   Cherbourg
174  56.0  First   Cherbourg
487  58.0  First   Cherbourg

In [ ]:
df["embark_town"].value_counts()

embark_town
Southampton    644
Cherbourg      168
Queenstown      77
Name: count, dtype: int64

In [ ]:
df_new = df.loc[( df["age"] > 50 )
& (df["sex"] == "male")
& ((df["embark_town"] == "Cherbourg") | (df["embark_town"]== "Southampton")),
["age","class","embark_town"]].head()

# | ya da demek , & ve demek

In [ ]:
df_new["embark_town"].value_counts()

embark_town
Southampton    3
Cherbourg      2
Name: count, dtype: int64

In [ ]:
#toplulaştırma ve gruplama (aggregation & grouping)
#- count()
#-first()
#-last()
#-mean()
#-median()
#-min()
#-max()
#-std()
#-var()
#-sum()
#-pivot table

In [ ]:
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns',None)
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df["age"].mean()

np.float64(29.69911764705882)

In [ ]:
df.groupby("sex")["age"].mean()

sex
female    27.915709
male      30.726645
Name: age, dtype: float64

In [ ]:
df.groupby("sex").agg({"age":"mean"})

              age
sex
female  27.915709
male    30.726645

In [ ]:
df.groupby("sex").agg({"age" : ["mean","sum"]})

              age
             mean       sum
sex
female  27.915709   7286.00
male    30.726645  13919.17

In [ ]:
df.groupby("sex").agg({"age":["sum","mean"],"embark_town": "count"})
#burada embark town detayları cıkmadı cinsiyete göre sayı hesapladı.
#pivot kullanmak lazım

             age            embark_town
             sum       mean       count
sex
female   7286.00  27.915709         312
male    13919.17  30.726645         577

In [ ]:
df.groupby("sex").agg({"age":["sum","mean"],"survived": "mean"})
#kadınların bir çoğu hayatta kalmış erkeklere göre

             age             survived
             sum       mean      mean
sex
female   7286.00  27.915709  0.742038
male    13919.17  30.726645  0.188908

In [ ]:
df.groupby(["sex","embark_town"]).agg({"age":"mean", "survived":"mean"})

                          age  survived
sex    embark_town
female Cherbourg    28.344262  0.876712
       Queenstown   24.291667  0.750000
       Southampton  27.771505  0.689655
male   Cherbourg    32.998841  0.305263
       Queenstown   30.937500  0.073171
       Southampton  30.291440  0.174603

In [ ]:
df.groupby(["sex","embark_town","class"]).agg({"age":"mean", "survived":"mean"})

/tmp/ipython-input-1231094227.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex","embark_town","class"]).agg({"age":"mean", "survived":"mean"})

                                 age  survived
sex    embark_town class
female Cherbourg   First   36.052632  0.976744
                   Second  19.142857  1.000000
                   Third   14.062500  0.652174
       Queenstown  First   33.000000  1.000000
                   Second  30.000000  1.000000
                   Third   22.850000  0.727273
       Southampton First   32.704545  0.958333
                   Second  29.719697  0.910448
                   Third   23.223684  0.375000
male   Cherbourg   First   40.111111  0.404762
                   Second  25.937500  0.200000
                   Third   25.016800  0.232558
       Queenstown  First   44.000000  0.000000
                   Second  57.000000  0.000000
                   Third   28.142857  0.076923
       Southampton First   41.897188  0.354430
                   Second  30.875889  0.154639
                   Third   26.574766  0.128302

In [ ]:
df.groupby(["sex","embark_town","class"]).agg({"age":"mean", "survived":"mean","sex":"count"})

/tmp/ipython-input-290865407.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex","embark_town","class"]).agg({"age":"mean", "survived":"mean","sex":"count"})

                                 age  survived  sex
sex    embark_town class
female Cherbourg   First   36.052632  0.976744   43
                   Second  19.142857  1.000000    7
                   Third   14.062500  0.652174   23
       Queenstown  First   33.000000  1.000000    1
                   Second  30.000000  1.000000    2
                   Third   22.850000  0.727273   33
       Southampton First   32.704545  0.958333   48
                   Second  29.719697  0.910448   67
                   Third   23.223684  0.375000   88
male   Cherbourg   First   40.111111  0.404762   42
                   Second  25.937500  0.200000   10
                   Third   25.016800  0.232558   43
       Queenstown  First   44.000000  0.000000    1
                   Second  57.000000  0.000000    1
                   Third   28.142857  0.076923   39
       Southampton First   41.897188  0.354430   79
                   Second  30.875889  0.154639   97
                   Third   26.574766  0.128302  265

In [ ]:
from pandas._config.config import set_option
#pivot table
import pandas as pd
import seaborn as sns
pd.set_option('display.max_columns',None)
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.pivot_table("survived","sex","embarked")
#ilki kesişimi verir, ikinci satırları , üçüncü sütunları

embarked         C         Q         S
sex
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [ ]:
df.pivot_table("survived","sex","embarked",aggfunc="std")

embarked         C         Q         S
sex
female    0.331042  0.439155  0.463778
male      0.462962  0.263652  0.380058

In [ ]:
df.pivot_table("survived","sex",["embarked","class"])

/tmp/ipython-input-662412260.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived","sex",["embarked","class"])

embarked         C                      Q                          S  \
class        First Second     Third First Second     Third     First
sex
female    0.976744    1.0  0.652174   1.0    1.0  0.727273  0.958333
male      0.404762    0.2  0.232558   0.0    0.0  0.076923  0.354430

embarked
class       Second     Third
sex
female    0.910448  0.375000
male      0.154639  0.128302

In [ ]:
#cut ve qcut sayısal değişkenleri katogorik değkene çevirir
#cut hangi kategoiye böleceğin belliyse
#qcut ise çeyreklik bölümlere ayırır
#yaş değişkennini yorumladığım içn cut ı kullanırım 60 yaş üstü yaşlı dedim mesela
df["new_age"]=pd.cut(df["age"],[0, 10, 18, 25, 40, 90])

In [ ]:
df.pivot_table("survived", "sex", "new_age")

/tmp/ipython-input-510372881.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", "sex", "new_age")

new_age   (0, 10]  (10, 18]  (18, 25]  (25, 40]  (40, 90]
sex
female   0.612903  0.729730  0.759259  0.802198  0.770833
male     0.575758  0.131579  0.120370  0.220930  0.176471

In [ ]:
df.pivot_table("survived", "sex", ["new_age","class"])

/tmp/ipython-input-2130583655.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", "sex", ["new_age","class"])

new_age (0, 10]                   (10, 18]                   (18, 25]  \
class     First Second     Third     First Second     Third     First
sex
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333

new_age                      (25, 40]                      (40, 90]            \
class      Second     Third     First    Second     Third     First    Second
sex
female   0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154
male     0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238

new_age
class       Third
sex
female   0.111111
male     0.064516

In [ ]:
pd.set_option('display.width',500)#bütün kolonları tek satırda yazar

In [ ]:
df.pivot_table("survived", "sex", ["new_age","class"])

/tmp/ipython-input-866978728.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", "sex", ["new_age","class"])

new_age (0, 10]                   (10, 18]                   (18, 25]                      (25, 40]                      (40, 90]
class     First Second     Third     First Second     Third     First    Second     Third     First    Second     Third     First    Second     Third
sex
female      0.0    1.0  0.500000  1.000000    1.0  0.523810  0.941176  0.933333  0.500000  1.000000  0.906250  0.464286  0.961538  0.846154  0.111111
male        1.0    1.0  0.363636  0.666667    0.0  0.103448  0.333333  0.047619  0.115385  0.513514  0.071429  0.172043  0.280000  0.095238  0.064516